// Code generated by mockery v2.1.0. DO NOT EDIT.

package mocks

import (
	dns "github.com/miekg/dns"
	mock "github.com/stretchr/testify/mock"
)

// DNSOps is an autogenerated mock type for the DNSOps type
type DNSOps struct {
	mock.Mock
}

// ClientConfigFromFile provides a mock function with given fields: resolvconf
func (_m *DNSOps) ClientConfigFromFile(resolvconf string) (*dns.ClientConfig, error) {
	ret := _m.Called(resolvconf)

	var r0 *dns.ClientConfig
	if rf, ok := ret.Get(0).(func(string) *dns.ClientConfig); ok {
		r0 = rf(resolvconf)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dns.ClientConfig)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(resolvconf)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Fqdn provides a mock function with given fields: s
func (_m *DNSOps) Fqdn(s string) string {
	ret := _m.Called(s)

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(s)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}
